### ISSUE TITLE
Add BuddyBuild Android support

### ISSUE THREAD

**Issue by eugenehp** [luggit/react-native-config#135]
There are a lot of default scripting involved in `dotenv.gradle`, so it would be great to make it customisable.

### What BuddyBuild runs in cloud
`gradle --no-daemon ":app:assemble"`

### What to use to run it locally
`cd android && ./gradlew  --no-daemon ":app:assemble"`

### Output from BuddyBuild CLI.

<img width="1144" alt="screen shot 2017-07-22 at 09 20 01" src="https://user-images.githubusercontent.com/1857263/28492810-018118b2-6ebf-11e7-824f-bced28c463f0.png">

P.S. iOS works just fine with different Schemas!

**Comment by hdchan** [comment]
I created a pull request to address this: https://github.com/luggit/react-native-config/pull/180

**Comment by pedro** [comment]
Fixed in #180.

**Comment by jmeiss** [comment]
@eugenehp I was wondering if you succeed to make it works with buddybuild and react-native-config v0.11.1?
I've been trying for few hours without any success.

When I execute `./gradlew --no-daemon ":app:assemble"` I always get the following error:
```
Reading env from: .env
**************************
*** Missing .env file ****
**************************
```

Here is my config in build.gradle:

```
project.ext.envConfigFiles = [
    developmentDebug: ".env.development",
    developmentRelease: ".env.development",

    stagingDebug: ".env.staging",
    stagingRelease: ".env.staging",

    productionDebug: ".env.production",
    productionRelease: ".env.production"
]

...


    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    productFlavors {
        development {
            resValue "string", "app_name", "FooBar DEV"
            applicationIdSuffix ".dev"
        }

        staging {
            resValue "string", "app_name", "FooBar STAGING"
            applicationIdSuffix ".staging"
        }

        production {
            resValue "string", "app_name", "FooBar"
        }
    }
```

But I'm still facing an issue:
```
/tmp/sandbox/workspace/android/app/build/intermediates/manifests/full/production/release/AndroidManifest.xml:102:28-51: AAPT: No resource found that matches the given name (at 'value' with value '@string/FACEBOOK_APP_ID').
```

Which is related to a variable present in our `.env.*` files.

So I'm wondering if you finally made it work?

**Comment by fforres** [comment]
I'm dealing exactly with the same error. Found a solution @jmeiss (or any ideas @eugenehp @pedro @hdchan ?)

I'm guessing it's a config problem more than anything

**Comment by jmeiss** [comment]
Nope, still no solution on that :/

I had a conversation yesterday with someone from BuddyBuild and basically the answer I got is: `We don't build each flavour separately, but if you can get things running locally it should work on buddybuild.`

**Comment by songxiaoliang** [comment]
@jmeiss hi， Is this problem solved?
