### ISSUE TITLE
react-native-config example does not read variables from .env file or .env.prod 

### ISSUE THREAD

**Issue by nomaannomii** [luggit/react-native-config#170]
Windows 10
Mobile Device Nexus 6P
react-native-cli: 2.0.1
react-native: 0.38.1
SET ENVFILE='.env.prod' && react-native run-android

when i run above line on example application its not reading anything from .env file.

**Comment by pedro** [comment]
Did you do the Android setup?

https://github.com/luggit/react-native-config#extra-step-for-android

**Comment by vdesdoigts** [comment]
Same problem, even with 
```
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```

**Comment by pedro** [comment]
Can you paste the output of `react-native run-android`?

When it's setup properly you can see it's reading (or failing to read) the env like:

```
$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug...
Reading env from: .env
...
```

**Comment by vdesdoigts** [comment]
It's fine with`react-native run-android`
```
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Reading env from: .env
...
```

But when I want to build an apk for release, `config.ROOT_URL` is undefined, there is my `.env.prod`
```
ENV=prod
ROOT_URL=https://playgrounds-app.com
```

**Comment by vdesdoigts** [comment]
No fail spotted 🤔 
```
$ ENVFILE=.env.prod cd android && ./gradlew assembleRelease
Reading env from: .env
```

**Comment by pedro** [comment]
Oh! How are you setting it to use `.env.prod`? What are you calling to build the apk?

**Comment by pedro** [comment]
ah hmm. Does it work if you `export ENVFILE=.env.prod` instead of setting it this way?

**Comment by vdesdoigts** [comment]
I also have a .env, so `Reading env from: .env` should work
```
ENV=prod
ROOT_URL=https://playgrounds-app.com
```

How I use it in my app :
```
import Config from 'react-native-config';

const axiosConfig = {
  baseURL: `${Config.API_URL}`,
  responseType: 'json',
  headers: { 'Content-Type': 'application/json' },
};
```

Logs when I launch my app (signed) : `java.lang.IllegalArgumentException: unexpected url: undefined/playgrounds/around_me?latitude=48.85661166666667&longitude=2.3522216666666664&distance=5`

**Comment by vdesdoigts** [comment]
I also see this `:react-native-config:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).` but I'm not sure it's relevant.

**Comment by pedro** [comment]
Ah weird, so you see "Reading env from .env" when you call `gradlew assembleRelease` too?

I never had this issue myself, but wondering if it's because of a custom applicationId/applicationIdSuffix, or Proguard.

Have you checked the [advanced setup and troubleshooting sections here](https://github.com/luggit/react-native-config#advanced-android-setup)?

**Comment by pedro** [comment]
Maybe clean the build too to be sure: `cd android/ && ./gradlew clean`

**Comment by vdesdoigts** [comment]
I change my `applicationId` and it works! Don't know exactly why.  
I used `com.playgrounds.app`, it works with `com.playgrounds`, which was the default id.
Thanks for your time 🙏

**Comment by pedro** [comment]
Ah, phew!

Surprised this didn't cause a compilation failure in 1st place :| hopefully we can fix this at some point.

But thank you! Closing this for now.

**Comment by Ayyagaries** [comment]
I am unable to solve this problem. with the provided solutions

**Comment by CodeAmend** [comment]
It seems the issue for me I needed to add 

`new ReactNativeConfigPackage(),` in the `MainApplication.java`

**Comment by AndreyPatseiko** [comment]
Have the same problem. I can get environment variable when just run react-native run-android, but if I try create sign apk a just  can't get values. ((

**Comment by AndreyPatseiko** [comment]
For use this constants you mast **exported** it. And you can't use other assemble type, only **assembleRelease**. If you create other build type in build.gradle, simple copy release, this don't work. 
    
    "build-staging:android": "export ENVFILE=.env.staging && cd android && ./gradlew assembleRelease",

Please add in documentation section "How install manual" - because I spend many time for run lib, because `react-native link` doesn't work on me.

**Comment by aecc** [comment]
> It seems the issue for me I needed to add
> 
> `new ReactNativeConfigPackage(),` in the `MainApplication.java`

I was days trying to figure out why my react Config variable was always empty. That solved it. This NEEDS to be added to the README!

Also the import is:
import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;

**Comment by pradhul** [comment]
for me I was using build variants and adding BuildConfig to progurad file solved it.

**Comment by AdamZaczek** [comment]
I already had ```new ReactNativeConfigPackage()``` inside ```MainApplication.java``` but I had to put it after all the CodePush related stuff. Hope this helps someone!

**Comment by RunnableWeb** [comment]
for react native 0.60.0, I have fixed it adding `new ReactNativeConfigPackage()` manually like so:
 ```
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new ReactNativeConfigPackage());
      
      return packages;
    }
```
it seems that react native autolinking feature not implemented in this package yet

**Comment by hisankaran** [comment]
When we select APK from app bundle in the deploy option, Gradle runs a task named `extractApksForFlavour` which breaks this regex: https://github.com/luggit/react-native-config/blob/master/android/dotenv.gradle#L10. So make sure that you choose Default APK option when running on device. <img width="1070" alt="Screenshot 2019-07-15 at 5 08 21 PM" src="https://user-images.githubusercontent.com/501259/61213620-2ea88200-a723-11e9-9f19-28a9c344d0f9.png">

**Comment by LuizFBrisighello** [comment]
> for me I was using build variants and adding BuildConfig to progurad file solved it.

@pradhul  Can you explain how you did that?

**Comment by bericp1** [comment]
For `react-native@0.60.5` released yesterday it seems like it's no longer required to manually add the package and in fact when you do you get an error. Autolinking appears to work out of the box now for this package on `react-native@^0.60.5`.

I installed running the following:

```
$ yarn add react-native-config
$ cd ios && pod install && cd ../
```

And then I made the manual updates that the README specifies for Android and iOS:

1.  Adding `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"` to `android/app/build.gradle`
2.  Adding `-keep class com.mypackage.BuildConfig { *; }` to `android/app/proguard-rules.pro`
3.  Adding pre-build scripts in XCode to be able to use variables in Info.plist and project build settings.

And everything just... worked. In both iOS and Android.

So I think the only thing that's needed is notes in the `README`:

> If your react-native version is `< 0.60.0`, follow the linking steps below.
> If your react-native version is `>= 0.60.0` and `< 0.60.5`, you still need to follow the linking steps below but you need to additionally manually register the package by editing `MainApplication.java` to add `packages.add(new ReactNativeConfigPackage());` in the `getPackages` method.
> If your react-native version is `> 0.60.0` this package will work with the autolinker and you don't need to manually run any command to link the package outside of running `pod install` in the `ios` directory per the [`react-native-community/cli` docs](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md).
>
> **Note:** for any RN version (including autolinking) you still need to perform the "extra steps" described below.

Or something to that effect.

**Comment by LuizFBrisighello** [comment]
@bericp1 I started using RN 0.60.5 and for simple `$env:ENVFILE=".env.mycustomenv"; react-native run-android` works fine! But adding productFlavors in that mix fucks me up.
Running `$env:ENVFILE=".env.mycustomenv"; react-native run-android --variant=myvariantDebug`

I still get:
`> Configure project :app
Reading env from: aquicard2.env`

but `Config.MY_ENV_VAR` always returns `undefined`

**Comment by conor909** [comment]
@aecc ifg I add `import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;`

and then add `new ReactNativeConfigPackage()`

I get `error: package com.lugg.ReactNativeConfig does not exist`

Am I missing an install step?

**Comment by waqaramjad** [comment]
i tried all but nothing resolve my issue , still get undefine

**Comment by waqaramjad** [comment]
> ly

can you give some example that where we run that command because export give error , or may be some other things

**Comment by kevinnath1007** [comment]
> I change my `applicationId` and it works! Don't know exactly why.
> I used `com.playgrounds.app`, it works with `com.playgrounds`, which was the default id.
> Thanks for your time 🙏

so you need to change aplicationId to default id..??
I tried to change all my version code applicationId so I can define it as another app, but it always returns undefined even though successfully build, can you help..??

**Comment by harastaivan** [comment]
I was updating my app from React Native 0.57 to 0.61.3 ran into a lot of issues and *unlinked all packages*, since newer React Native introduced auto-linking.
- That didn't work so I needed link it back: `react-native link react-native-config`.
- That still wasn't enough so I needed to add `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"` on the 2nd line of `android/app/build.gradle`, because I didn't have it there before the update.

**Comment by chepitoco** [comment]
It works for me: 

Adding -keep class com.mypackage.BuildConfig { *; } to android/app/proguard-rules.pro

**Comment by elijahmurray** [comment]
I got this working through some experimentation. For me, I'm using `yarn workspaces` so my `node_modules` folder is up a directory, and that's why it was failing. I just replaced the suggested line with a direct import of the needed file.

In your `app/build.gradle`, when the `react-native-config` docs ask for:

`apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`

Replace it with:

`apply from: "../../node_modules/react-native-config/android/dotenv.gradle"`

Or in my case and using `yarn workspaces`, replace it with:

`apply from: "../../../node_modules/react-native-config/android/dotenv.gradle"`

**Comment by parnekov** [comment]
> Did you do the Android setup?
> 
> https://github.com/luggit/react-native-config#extra-step-for-android

**Works!**

**Comment by dipeshkoirala21** [comment]
@LuizFBrisighello Hi, did you resolve your undefined issue with Product Flavor? I am getting undefined too.

**Comment by nitzanw** [comment]
me too! what's the solution?

**Comment by LuizFBrisighello** [comment]
@dipeshkoirala21 Sorry for the late answer and its not a very good news, at the time I figured out but now it was over a year ago.. I really dont remeber.

Im still on RN 0.60.5, using `react-native-config` 0.11.7
I think following extra-step-for-android in the link down bellow fixes it

> Did you do the Android setup?
> 
> https://github.com/luggit/react-native-config#extra-step-for-android

**Comment by mahisaajy** [comment]
> Did you do the Android setup?
> 
> https://github.com/luggit/react-native-config#extra-step-for-android

it works for us

**Comment by ePoromaa** [comment]
In our case, we could not read the .env file because we used a suffix for our application name, `(.qa)`.
Adding `resValue "string", "build_config_package", "com.our_app" ` as such to the `android/app/build.gradle` solved it for us:
``` 
...
   productFlavors {
        dev {}
        qa {
            applicationId 'com.our_app.qa'
            resValue "string", "build_config_package", "com.our_app" // Required for react-native-config to find .env
        }
    }
...
```

**Comment by cutePanda123** [comment]
After I installed react-native-config and added the .env file to my project's root, I found the environment variables were still not included in the Config object.
I tried all the mitigation approaches without making it work. Finally, I double-checked the react-native-config package's instruction(https://github.com/luggit/react-native-config) and found the extra step for Android matters. As I am focusing on building an Android app now, I have not verified if iOs works or not.

```
Extra step for Android
You'll also need to manually apply a plugin to your app, from android/app/build.gradle:

// 2nd line, add a new apply:
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv
```

In a summary, what I did to make it work:
1. yarn add react-native-config
2. npx react-native link react-native-config
3. Note: for the above step, it seems like adding "new ReactNativeConfigPackage()" to MainApplication.java is not needed. I tried to add it and got an error from the Android emulator indicated that this package was added twice.
4. Add "apply from: project(':react-native-config').projectDir.getPath() + "/dotenv" to the 2nd line of android/app/build.bradle
5. npx react-native run-android
6. It just worked \^w^/ 

My changes can be found from this commit
https://github.com/cutePanda123/pure-listener/commit/b406e04a84ab0cf72cc0f6de345ad1e59dfa5998

**Comment by MGhufranKhalil** [comment]
> Did you do the Android setup?
> 
> https://github.com/luggit/react-native-config#extra-step-for-android

work for  me

**Comment by WillyRamirez** [comment]
> I was updating my app from React Native 0.57 to 0.61.3 ran into a lot of issues and _unlinked all packages_, since newer React Native introduced auto-linking.
> 
> * That didn't work so I needed link it back: `react-native link react-native-config`.
> * That still wasn't enough so I needed to add `apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"` on the 2nd line of `android/app/build.gradle`, because I didn't have it there before the update.

this worked for me. 
I am on
    "react-native": "0.64.0",
    "react-native-config": "^1.4.2",

**Comment by blazlew** [comment]
> In our case, we could not read the .env file because we used a suffix for our application name, `(.qa)`.
> Adding `resValue "string", "build_config_package", "com.our_app" ` as such to the `android/app/build.gradle` solved it for us:
> 
> ```
> ...
>    productFlavors {
>         dev {}
>         qa {
>             applicationId 'com.our_app.qa'
>             resValue "string", "build_config_package", "com.our_app" // Required for react-native-config to find .env
>         }
>     }
> ...
> ```

Thanks, it was also my issue. You can use the `applicationIdSuffix` for each flavor instead of providing full package name every time.
Also, I was able to resolve the issue for all flavors using `applicationIdSuffix` in one place like so:
```
...
defaultConfig {
        applicationId "com.our_app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        resValue "string", "build_config_package", applicationId
    }
...
```

**Comment by xgenem** [comment]
Figured the issue is related to different applicationId. Only when different this plugin won't work.

**Comment by yogendrajs** [comment]
Hey, this is working for debug mode, but not for staging/prod for Android. I've done everything provided above. Any workaround? Also, what if I want to access `.env.prod`?

**Comment by yogendrajs** [comment]
Hey, this is working for debug mode, but not for staging/prod for Android. I've done everything being provided above. Any workaround? Also, what if I want to access `.env.prod`?

**Comment by Eliajn** [comment]
![Screen Shot 2021-12-02 at 12 27 49 AM](https://user-images.githubusercontent.com/34067448/144324349-9c7340d5-c65a-4484-a94d-8bbc60e021bd.png)

I am trying to create a signed bundle release from android studio preview, after the build is successful, the env variable  does not exist, after extracting and apk file from the bundle release and trying it on an android device.

**Comment by SirCameron** [comment]
Is there a solution to this? 
when I run `ENVFILE=.env.staging npx react-native run-android --variant=release`

I get this in the output:
```
> Configure project :app
Reading env from: .env.staging
```

this all works without variant=release.

**Comment by Y-k-Y** [comment]
`-keep class com.mypackage.BuildConfig { *; }` in `android/app/proguard-rules.pro` worked for me!

### My environment
- RN 69.1
- react-native-config 1.4.6

**Comment by buuhvprojects** [comment]
> Windows 10 Mobile Device Nexus 6P react-native-cli: 2.0.1 react-native: 0.38.1 SET ENVFILE='.env.prod' && react-native run-android
> 
> when i run above line on example application its not reading anything from .env file.

Its simple but unexpected. Doesnt use import { SOME_ENV }  from 'react-native-config'; when build it, the lib doenst reconize it. You need always use: import Config from 'react-native-config'; so Config.SOME_ENV

**Comment by SanjanaTailor** [comment]
> @bericp1 I started using RN 0.60.5 and for simple `$env:ENVFILE=".env.mycustomenv"; react-native run-android` works fine! But adding productFlavors in that mix fucks me up. Running `$env:ENVFILE=".env.mycustomenv"; react-native run-android --variant=myvariantDebug`
> 
> I still get: `> Configure project :app Reading env from: .env.mycustomenv`
> 
> but `Config.MY_ENV_VAR` always returns `undefined` Any ideas?

I am also facing an issue.

**Comment by markmarkoh** [comment]
We were having this issue because of Proguard, as far as I could tell. Disabling Proguard in our release builds fixed it, but obviously we wanted Proguard back in.

I fixed this issue using the `-keep class` in the `proguard-rules.pro` file mentioned here: https://www.npmjs.com/package/react-native-config/v/0.11.6#problems-with-proguard

The important part is:
> Problems with Proguard
> When Proguard is enabled (which it is by default for Android release builds), it can rename the BuildConfig Java class in the minification process and prevent React Native Config from referencing it. To avoid this, add an exception to android/app/proguard-rules.pro:
>
> -keep class com.mypackage.BuildConfig { *; }
> **mypackage should match the package value in your app/src/main/AndroidManifest.xml file.** <-- super important

**Comment by RanvijayChouhan12** [comment]
### **Finally i have Solved the Issue**

**To Ceate the REACT_NATIVE_CONFIG** https://github.com/luggit/react-native-config
### follow the Above setup to to install and After installetion follow this 

1. Create Your .env File such as .env , .env.production , .env.test etc in your Root of the Project

2. in **android/settings.gradle**  Paste the Below Lines

```
include ':react-native-config'
project(':react-native-config').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-config/android')

```
3. in **android/app/build.gradle**  paste the below Line just below the **apply plugin: "com.android.application"**

```
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
OR
apply from: "../../node_modules/react-native-config/android/dotenv.gradle"
```

Then 
```
project.ext.envConfigFiles = [
    dev: ".env",
    test: ".env.test",
    production: ".env.production",
]
```

make Changes as your Requirements

**THEN**   add these Configs just Above the  : **defaultConfig**

```
flavorDimensions "default"
    productFlavors {
        Dev {
            applicationId "com.myapp.app"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
            buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
            resValue "string", "build_config_package", "com.myapp.app"
        }
        Test {
            applicationId "com.myapp.app"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
            buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
            resValue "string", "build_config_package", "com.myapp.app"
        }
        Production {
            applicationId "com.myapp.app"
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
            versionCode 1
            versionName "1.0"
            buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
            resValue "string", "build_config_package", "com.myapp.app"
        }
    }
```

also don't Forget tio ADD at the end of your **defaultConfig**

`  resValue "string", "build_config_package", "com.myapp.app"`

**THEN** ADD 
`matchingFallbacks = ['debug', 'release']`

in the buildTypes.debug


in the **dependencies** add 
`implementation project(':react-native-config')`

4. in **android/app/proguard-rules.pro**  Paste the Below Line

`-keep class com.transportsimple.appId.BuildConfig { *; }`

**NOTE :**   Please replace **com.transportsimple.appId** with your APP Package 


Your are DONE for the ANDROID Setup of the .env File

Now to Run the APP  Please run the following command.

```
"android": "react-native run-android --variant=devDebug -- --reset-cache",
"android:release": "react-native run-android --variant=devRelease",
"android:test": "react-native run-android --variant=testDebug",
"android:test-release": "react-native run-android --variant=testRelease",
"android:prod": "react-native run-android --variant=productionDebug",
"android:prod-release": "react-native run-android --variant=productionRelease",
```

to Build the APK Please do the Following:

```
"android:build_apk-dev": "export ENVFILE=.env && cd android && ./gradlew assembleDevRelease",
"android:build_apk-test": "export ENVFILE=.env.test && cd android && ./gradlew assembleTestRelease",
"android:build_apk-prod": "export ENVFILE=.env.production && cd android && ./gradlew assembleProductionRelease",
```

To Build AAB File run Folllowing :

```
"android:build_aab-dev": "export ENVFILE=.env && cd android && ./gradlew bundleDevRelease",
"android:build_aab-test": "export ENVFILE=.env.test && cd android && ./gradlew bundleTestRelease",
"android:build_aab-prod": "export ENVFILE=.env.production && cd android && ./gradlew bundleProductionRelease"
```

**Comment by humayunkabir** [comment]
> Same problem with `ENVFILE=.env.prod cd android && ./gradlew assembleRelease` , even with
> 
> ```
> apply plugin: "com.android.application"
> apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
> ```
> 
> Working fine with `react-native run-android` debug mode.

This works for me, Thanks a lot.

**Comment by mohamedibnelazzouzi** [comment]
> It works for me:
> 
> Adding `-keep class com.mypackage.BuildConfig { *; } to android/app/proguard-rules.pro`
