### ISSUE TITLE
GeneratedInfoPlistDotEnv.h' file not found

### ISSUE THREAD

**Issue by Deno028** [luggit/react-native-config#83]
I created a new scheme with new Configuration build : **releaseDev**

"react-native": "0.37.0",
 "react-native-config": "^0.3.0",

**When archiving I got this error:** 

_fatal error: '/Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-xxx/Build/Intermediates/ArchiveIntermediates/myDevScheme/BuildProductsPath/ReleaseDev-iphoneos/GeneratedInfoPlistDotEnv.h' file not found_

**Notes:** it works with default configuration builds: **release** and **debug**.

**Comment by christophby** [comment]
Same here

**Comment by stakkdarren** [comment]
same here

**Comment by darrenchiu** [comment]
same here

**Comment by robbykim** [comment]
+1

**Comment by l3wi** [comment]
+1

**Comment by iamrutvik** [comment]
+1,

Even after linking it did not work

**Comment by CoreyAR** [comment]
I had this problem using a previous version of react-native-config. I was able to resolve it by updating to 0.3.0, unlinking react-native-config, cleaning my project, and deleting ios/build.

**Comment by cristianrosu** [comment]
Make sure you do the preprocess settings under Build Settings while having the main project selected, not a target. 😄

**Comment by Deno028** [comment]
@CoreyAR: I try both 0.3.0 and 0.3.1 unlink and relink but still failed. Are you using with multi build configurations instead of default "release and debug"?

@cristianrosu : This error throw from preprocessor.

**Comment by Deno028** [comment]
I find that the BuildDotenvConfig.ruby wrote to wrong file:
Because the value of ENV["CONFIGURATION_BUILD_DIR"] diffrent with ${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h in Preprocessor Prefix Info.plist config.


> Reading env from .env.dev
> Wrote to /Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-agbpncwqiroipybewdcexatgmqjc/Build/Products/**Release-iphoneos**/GeneratedInfoPlistDotEnv.h

**But the preprocess script check the link:**

>  fatal error: '/Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-agbpncwqiroipybewdcexatgmqjc/Build/Products/**ReleaseDev-iphoneos**/GeneratedInfoPlistDotEnv.h' file not found
> #include "/Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-agbpncwqiroipybewdcexatgmqjc/Build/Products/**ReleaseDev-iphoneos**/GeneratedInfoPlistDotEnv.h"

**Comment by Deno028** [comment]
After all I find the solution for this : 

**Set the value for Info.plist Preprocessor Prefix File**
${SYMROOT}/Release$(EFFECTIVE_PLATFORM_NAME)/GeneratedInfoPlistDotEnv.h

**Instead of the one from documentation:**
${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h

**Comment by masiamj** [comment]
+1 - great fix @Deno028

**Comment by wholcman** [comment]
Try to double check if there is no space when you copy/paste ${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h in the preprocessor prefix file.

**Comment by Johan-dutoit** [comment]
Any solution for this?

**Comment by Deno028** [comment]
@Johan-dutoit : What problem have you got? Any error message?

**Comment by iamrutvik** [comment]
Upgrade or downgrade library version based on your react native version. I was using RN 0.38 and I was using latest version of react native config. I had to downgrade config version to make it work

**Comment by jordanmkoncz** [comment]
I was getting this error for a new "Staging" scheme I had created. The standard release scheme was working but the Staging scheme was not. @Deno028 your suggestion worked for me.

**Comment by Johan-dutoit** [comment]
@Deno028 I eventually got it to work with the new config, using your above solution.  Guess it was just not cleaned/built correctly after I initially made the change.

**Comment by jinxac** [comment]
I faced similar issue when I removed the node_modules folder to check something. Linking again using react-native also did not work.

So, tried unlinking and linking it again.

```
react-native unlink react-native-config
react-native link react-native-config
```

After this it works fine for me

**Comment by PeterRock** [comment]
I fix it.
Set the value for Info.plist Preprocessor Prefix File
$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/GeneratedInfoPlistDotEnv.h

**Comment by eugenehp** [comment]
I also found that `INFOPLIST_PREFIX_HEADER` should be adjusted as well. See my changes here: https://github.com/eugenehp/react-native-config/commit/9792326107a3204110c723dfee244f8d067bb786

**Comment by ngnclht1102** [comment]
@eugenehp Event I've changed `INFOPLIST_PREFIX_HEADER ` like you, but I check the real folder in Finder, I didn't see any GeneratedInfoPlistDotEnv.h. file yet

**Comment by ujwal-setlur** [comment]
I had to set it to the ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h

Looking at the BuildDotenvConfig.ruby file, it writes the header file to:

```
# write it so the Info.plist preprocessor can access it
path = File.join(ENV["BUILD_DIR"], "GeneratedInfoPlistDotEnv.h")
File.open(path, "w") { |f| f.puts info_plist_defines_objc }
```

So, I ended up changing the Info.plist Preprocessor Prefix File setting to ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h

This has to be done for the Project and all targets. In my case, in three places.

**Comment by xilibro** [comment]
I install the latest version, and i found difference between README.md and web page

**Comment by cocymsc1986** [comment]
@pedro will one of the above be accepted? There a few different answers here, seems to be different things work for different people.

**Comment by PolGuixe** [comment]
In my case I couldn't find any. Is there way to better debug the process?

**Comment by digitaldavenyc** [comment]
Changing `Info.plist Preprocessor Prefix File` to `${BUILD_DIR}/GeneratedInfoPlistDotEnv.h`worked for me as well. 

I looked in the build directory and it seems the path for `CONFIGURATION_BUILD_DIR` looks inside `Debug-iphonesimulator` directory. The `GeneratedInfoPlistDotEnv.h` is a directory above this in `ios > build > Build > Products > GeneratedInfoPlistDotEnv.h`

**Comment by fabriziomoscon** [comment]
I wasted a couple of hours with this issue as well... using version `5.0.0` and RN `0.45.1`
The app was building for all SCHEMES using a Build Settings `Release` but not for `Debug`.

I fixed by applying this patch to my `ios/MyApp.xcodeproj/project.pbxproj`

```diff
- ONLY_ACTIVE_ARCH = NO;
+ ONLY_ACTIVE_ARCH = YES;

- INFOPLIST_PREFIX_HEADER = "$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/GeneratedInfoPlistDotEnv.h";
+ INFOPLIST_PREFIX_HEADER = "${BUILD_DIR}/GeneratedInfoPlistDotEnv.h";
```

I really hope this could help somebody else not to waste time!

**Comment by linhnh123** [comment]
You can try, it work for me:
`
react-native run-ios
`
Then you must be close and reopen the XCode, clean and build.

**Comment by Knight704** [comment]
@xilibro thanks man, you saved my day!
All: in a nutshell the correct value for Preprocessor Prefix File is equal to ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h

**Comment by yomybaby** [comment]
@mikefrancis, you save my time. 😄

**Comment by RyanMcDonald** [comment]
I fixed this problem by manually linking libReactNativeConfig. `react-native link` seems to only link the default scheme and not custom ones. So when the custom scheme is built, react-native-config never gets built, so the `GeneratedInfoPlistDotEnv.h` file is never created.

Select your project > choose your target > General > Linked Frameworks and Libraries > Click the + > search for libReactNativeConfig.

**Comment by chandureddivari** [comment]
Worked for me after adding `${BUILD_DIR}/GeneratedInfoPlistDotEnv.h` in build settings after choosing the target

**Comment by AmandeepSingh06** [comment]
@RyanMcDonald: How did you find the libReactNativeConfig.a file in the workspace?

**Comment by RyanMcDonald** [comment]
@AmandeepSingh06 `react-native link` should add `libReactNativeConfig.a` to the workspace.

**Comment by DLevai94** [comment]
Still an issue. New React Native project with cocoapods, properly installed, then tried everything in this thread. Nothing...

**Comment by ifero** [comment]
Hello everyone. I've found a very ugly but efficient solution.

If you're using cocoapods, Xcode will try to build react-native-config pod project first.
The thing that I've noticed is that ```BuildDotenvConfig.ruby``` is never executed so that there is no way in which you will find the **GeneratedDotEnv.m** or the  **GeneratedInfoPlistDotEnv.h**.

What I did was to create a .sh file in my project root:

```
cd project-root 
vi build-prod-env.sh
```
inside build-prod-env.sh:
```
#!/bin/sh

export ENVFILE=".env.production"
export SYMROOT="./ReactNativeConfig"
export BUILD_DIR="../../../ios/build/Build/Products"
cd ./node_modules/react-native-config/ios
echo "----- Start Config -----"
ruby ./ReactNativeConfig/BuildDotenvConfig.ruby
echo "----- Building App -----"
cd -
react-native run-ios
```

- SYMROOT is needed to generate _GeneratedDotEnv.m_
- BUILD_DIR is needed to generate _GeneratedInfoPlistDotEnv.h_

This solution worked for me and I have created different .sh file based on the target and .env file to use

**Comment by wwan5803** [comment]
Well, my solution is to run **yarn install react-native-config**. As I pull my code from github, then I did npm install. All other package installed except react-native-config.

**Comment by wswebcreation** [comment]
For all people who are also struggling with this, [this](https://github.com/luggit/react-native-config/issues/125#issuecomment-350134781) answer might help. We are on react-native 0.51 and I couldn't get it working. Downgrading, linking and upgrading it helped.

**Comment by loonison101** [comment]
@RyanMcDonald 's adding of the library worked for me. I had to do some manual steps:

- Drag from node modules/react-native-config/ios/[xcode project file]
![image](https://user-images.githubusercontent.com/3193546/35695901-d3145538-0753-11e8-9d15-e4fd7e76d875.png)
- To here in Xcode under "libraries"
![image](https://user-images.githubusercontent.com/3193546/35696002-1ad4966c-0754-11e8-862f-b22ae5a445e3.png)
- And add the library under "linked frameworks and libraries"
![image](https://user-images.githubusercontent.com/3193546/35696049-4429a5e8-0754-11e8-8bf7-e7876426feca.png)

My error went away yelling about the "GeneratedInfoPlistDotEnv.h" not existing.

**Comment by ifero** [comment]
does anyone use frameworks?
My native project is in swift using cocoapods (thus I do need framework).
I really don't get how the GeneratedInfoPlistDotEnv.h will be generated.
It has to be created from the .ruby file that comes with the library. But when does it get runned? As my early message said, I did an ugly trick to run it manually, but of course I cannot build and run from Xcode with all the problems that comes with it.

**Comment by dancomanlive** [comment]
I just did the manual linking and I am getting React/RCTDefines.h' file not found. 

"react": "^16.0.0-beta.5",
"react-native": "^0.52.2"

**Comment by jinxac** [comment]
If someone is facing this issue on a customised configuration(other than `debug` and `release`) you can try `react-native-scheme-manager` to handle the configurations. I was facing same issue but with this package it works nicely.

**Comment by evanjmg** [comment]
Whenever you add a new target you either need to add manually or if you use cocoapods, make sure it gets added to the target their in your Podfile

**Comment by moroz0v** [comment]
> I install the latest version, and i found difference between README.md and web page
> In README.md:
> 
> * Set `Info.plist Preprocessor Prefix File` to `${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h`
> 
> on web page:
> Set Info.plist Preprocessor Prefix File to
> ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h
> 
> After i change my config as in READEME.md , it works well

Setting `${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h` on the project ONLY is what worked for me after trying everything else.

**Comment by ankitsehgal94** [comment]
> @RyanMcDonald 's adding of the library worked for me. I had to do some manual steps:
> 
> * Drag from node modules/react-native-config/ios/[xcode project file]
>   ![image](https://user-images.githubusercontent.com/3193546/35695901-d3145538-0753-11e8-9d15-e4fd7e76d875.png)
> * To here in Xcode under "libraries"
>   ![image](https://user-images.githubusercontent.com/3193546/35696002-1ad4966c-0754-11e8-862f-b22ae5a445e3.png)
> * And add the library under "linked frameworks and libraries"
>   ![image](https://user-images.githubusercontent.com/3193546/35696049-4429a5e8-0754-11e8-8bf7-e7876426feca.png)
> 
> My error went away yelling about the "GeneratedInfoPlistDotEnv.h" not existing.

This is giving me linkers error.

**Comment by Shweta-Porwal** [comment]
I got this error when I forgot to run npm install inside my react native project before building the app. Steps followed : Went to react native project folder. Ran npm install from the Terminal. Restarted Xcode.Everything started working.

**Comment by harrisrobin** [comment]
Adding the following to my Podfile did it for me:

```

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    # Because: https://github.com/luggit/react-native-config/issues/365
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
      " && RNC_ROOT=./node_modules/react-native-config/"\
      " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
      " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
      
      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
 
  end
end
```

**Comment by sandeep-sethia** [comment]
> @xilibro thanks man, you saved my day!
> All: in a nutshell the correct value for Preprocessor Prefix File is equal to ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h

Didn't work for me. :(

**Comment by mehdihz** [comment]
I've changed the below configs in "Build Settings" of project

1. Info.plist Other Preprocessor Flags => -traditional
2. Info.plist Preprocessor Prefix File => ${BUILD_DIR}/GeneratedInfoPlistDotEnv.h
3. Preprocess Info.plist File => Yes

and it worked

**Comment by justinairbase** [comment]
If you're coming from React version 0.60 and above, you should be referencing the package from GitHub instead of NPM. The author hasn't released auto-linking support on NPM yet, even though it's already merged!?

Try these steps after you unlink and uninstall the existing version of `react-native-config`. Remember to revert to default Info.plist preprocessor settings in XCode build settings.

 1. `yarn add https://github.com/luggit/react-native-config.git`

 2. `cd ios && pod install`

You don't have to add any other post-install scripts, just run the app like usual and it should work fine. Make sure you undo any other fixes before doing this.

**Comment by nicolashemonic** [comment]
> If you're coming from React version 0.60 and above, you should be referencing the package from GitHub instead of NPM. The author hasn't released auto-linking support on NPM yet, even though it's already merged!?
> 
> Try these steps after you unlink and uninstall the existing version of `react-native-config`. Remember to revert to default Info.plist preprocessor settings in XCode build settings.
> 
> 1. `yarn add https://github.com/luggit/react-native-config.git`
> 2. `cd ios && pod install`
> 
> You don't have to add any other post-install scripts, just run the app like usual and it should work fine. Make sure you undo any other fixes before doing this.

`0.12` don't work with React Native `0.6+` auto linking or not. 
I was obliged to downgrade to `0.11.7` and link the module manually, thanks to:
https://github.com/luggit/react-native-config/issues/414#issuecomment-559014103

**Comment by Taylor123** [comment]
@nicolashemonic do you have the `GeneratedInfoPlistDotEnv.h` in any of the preprocessing build settings?

**Comment by denisdimitrov** [comment]
I no longer needed the dependency and I removed it and it's pods, however I kept getting the following error:

- **GeneratedInfoPlistDotEnv.h' file not found** 

The fix was simple yet time consuming:

1. Remove `${BUILD_DIR}/GeneratedInfoPlistDotEnv.h` from `Info.plist Preprocessor Prefix File`
2. Set `Preprocess Info.plist File` to `No`

**Comment by tpucci** [comment]
@nicolashemonic Perhaps this will help: https://github.com/luggit/react-native-config/issues/391#issuecomment-571948199

**Comment by mechazod** [comment]
@denisdimitrov Just followed your suggestion.

**Comment by rafaelmaeuer** [comment]
https://github.com/luggit/react-native-config/issues/391#issuecomment-632331803 describes how to generate the file, so it should give the right hint for anyone who needs to remove it.

**Comment by ElliDy** [comment]
> Setting `${CONFIGURATION_BUILD_DIR}/GeneratedInfoPlistDotEnv.h` on the project ONLY is what worked for me after trying everything else.

Thanks @moroz0v, this worked for me. Setting it ONLY on project and NOT on the targets is the secret here.

**Comment by lukewlms** [comment]
My solution was pretty specific - mine was failing only when testing with Detox, but working fine with normal `run-ios`.  I fixed it by changing this setting in my Detox build command:

`-derivedDataPath ios/build`

To point to the Xcode DerivedData directory, where the .h file can actually be found:

/Users/me/Library/Developer/Xcode/DerivedData/mobile2mr-xxxx

**Comment by blinkyweezy** [comment]
for anyone who couldn't find a solution, how i solved mine was to navigate to the folder that was mentioned in the error message. mine was `/Users/user/Library/Developer/Xcode/DerivedData/app-gehbcoezzoencvciaviqaurqghcg/Build` and ran this code in the terminal **at that folder**, `touch GeneratedDotEnv.m GeneratedInfoPlistDotEnv.h && echo  "#define DOT_ENV @{  };" >> GeneratedDotEnv.m`. cleaned the project and it worked :))

**Comment by GastonRosso** [comment]
If anyone is still having the problem, my issue was that I was opening Xcode in ios folder, what solved it for my was opening xcworkspace file from Xcode.

**Comment by Deno028** [comment]
Sorry guys, I've been offline for a while. I think new versions this issue was solved.

**Comment by spsaucier** [comment]
We fixed by removing the requirements for `GeneratedInfoPlistDotEnv.h`, since it's not recommended by the `react-native-config` Readme anymore, and then we followed the instructions towards Config.xcconfig enabling env vars in Info.plist: https://github.com/luggit/react-native-config#availability-in-build-settings-and-infoplist, making sure that our Info.plist was using the proper `$(VAR)` syntax.

**Comment by naveenprakash74** [comment]
I am using Apple M2 chip 
I fixed it by using rosetta mode and it is working fine for me 
go to Product->destination-> destination architecture -> select "show Rosetta Destination"
